name: "Pull Request"
description: "Fill out the following details to submit your PR."
title: "[PR]: "
body:
  - type: markdown
    attributes:
      value: |
        ## Summary
        Please briefly describe the changes.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe what this PR does.
      placeholder: |
        E.g. Fixes display bug with templates.
        E.g. Adds a template tab that users can manage all templates through.
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issue(s)
      description: Link related issues
      placeholder: |
        E.g. Fixes #14
        E.g. Adds #4
    validations:
      required: false

  - type: checkboxes
    id: changes
    attributes:
      label: Type of Changes
      options:
        - label: Feature
        - label: Bug fix
        - label: Documentation
        - label: Refactoring
        - label: Build
        - label: Other

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The author of this PR has read the CONTRIBUTING guidelines.
        - label: This PR follows the Code of Conduct.
        - label: This PR follows the project's style of coding and documentation.
        - label: Documentation related to this PR has been updated.
        - label: Blue Marble has been verified to work correctly for this PR.

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else reviewers should know?
